version: "3.7"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/ip.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
    # ports:
    #   - "80:80"
    # ports:
      # - target: 80
        # published: 80
        # mode: host