version: "3"
services:
  postgresql:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgresql_data:
