version: "3"
services:
  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: metabase
      MB_DB_HOST: mb_db
    ports:
      - "3000:3000"
    depends_on:
      - mb_db

  mb_db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: metabase
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
    volumes:
      - mb_db_data:/var/lib/postgresql/data
      - ./sql/metabase:/docker-entrypoint-initdb.d

volumes:
  mb_db_data:
