version: "3.7"
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aicso
      ME_CONFIG_MONGODB_ADMINPASSWORD: aicso2020

  mongo:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: aicso
      MONGO_INITDB_ROOT_PASSWORD: aicso2020

volumes:
  mongo_data:
